import type { Recipe } from '@/types'

// ── Curated Filipino Recipe Dataset ─────────────────────
// Covers staples TheMealDB doesn't serve (or serves thinly).
// Ingredient names are lowercased to match the matcher's
// normalization and the ids in src/lib/ingredients.ts.

// Intentionally invalid image path on an allowed host → RecipeImage
// catches onError and renders the 🍳 fallback. Avoids fabricating
// Wikimedia URLs that may drift.
const PLACEHOLDER = 'https://www.themealdb.com/images/media/meals/_local.jpg'

export const FILIPINO_RECIPES: Recipe[] = [
  {
    id: 'fil-chicken-adobo',
    name: 'Chicken Adobo',
    imageUrl: PLACEHOLDER,
    category: 'Chicken',
    area: 'Filipino',
    ingredients: ['chicken', 'soy sauce', 'vinegar', 'garlic', 'bay leaf', 'black pepper', 'water'],
    measurements: ['1 kg', '1/2 cup', '1/3 cup', '6 cloves', '3 pcs', '1 tsp', '1 cup'],
    steps: [
      'Combine chicken, soy sauce, vinegar, garlic, bay leaf, and pepper in a pot.',
      'Bring to a boil without stirring, then simmer covered for 25 minutes.',
      'Uncover and reduce the sauce until thick and glossy.',
      'Serve hot with steamed rice.',
    ],
  },
  {
    id: 'fil-pork-adobo',
    name: 'Pork Adobo',
    imageUrl: PLACEHOLDER,
    category: 'Pork',
    area: 'Filipino',
    ingredients: ['pork belly', 'soy sauce', 'vinegar', 'garlic', 'bay leaf', 'black pepper', 'water'],
    measurements: ['1 kg', '1/2 cup', '1/3 cup', '6 cloves', '3 pcs', '1 tsp', '1 cup'],
    steps: [
      'Sear pork belly cubes until browned.',
      'Add soy sauce, vinegar, garlic, bay leaf, pepper, and water.',
      'Simmer covered for 40 minutes until tender.',
      'Reduce sauce until it coats the pork.',
    ],
  },
  {
    id: 'fil-sinigang-baboy',
    name: 'Sinigang na Baboy',
    imageUrl: PLACEHOLDER,
    category: 'Pork',
    area: 'Filipino',
    ingredients: ['pork belly', 'tamarind', 'onion', 'tomato', 'kangkong', 'sitaw', 'labanos', 'eggplant', 'green pepper', 'fish sauce', 'water'],
    measurements: ['1 kg', '1 pack', '1 pc', '2 pcs', '1 bunch', '8 pcs', '1 pc', '1 pc', '2 pcs', '2 tbsp', '8 cups'],
    steps: [
      'Boil pork with onion and tomato for 45 minutes, skimming foam.',
      'Add labanos and simmer until tender.',
      'Add tamarind mix, eggplant, sitaw, and green pepper.',
      'Finish with kangkong and season with fish sauce.',
    ],
  },
  {
    id: 'fil-tinolang-manok',
    name: 'Tinolang Manok',
    imageUrl: PLACEHOLDER,
    category: 'Chicken',
    area: 'Filipino',
    ingredients: ['chicken', 'ginger', 'garlic', 'onion', 'fish sauce', 'sayote', 'malunggay', 'water'],
    measurements: ['1 kg', '2 inches', '4 cloves', '1 pc', '2 tbsp', '1 pc', '1 bunch', '6 cups'],
    steps: [
      'Sauté ginger, garlic, and onion in oil.',
      'Add chicken and fish sauce, cook until lightly browned.',
      'Pour in water and simmer for 25 minutes.',
      'Add sayote and cook until tender, then stir in malunggay.',
    ],
  },
  {
    id: 'fil-kare-kare',
    name: 'Kare-Kare',
    imageUrl: PLACEHOLDER,
    category: 'Beef',
    area: 'Filipino',
    ingredients: ['beef shank', 'peanut butter', 'annatto', 'garlic', 'onion', 'eggplant', 'sitaw', 'pechay', 'bagoong', 'water'],
    measurements: ['1 kg', '1/2 cup', '2 tbsp', '4 cloves', '1 pc', '2 pcs', '10 pcs', '1 bunch', 'to serve', '8 cups'],
    steps: [
      'Boil beef shank until fork-tender, about 2 hours. Reserve broth.',
      'Sauté garlic and onion, add annatto water and broth.',
      'Stir in peanut butter until the sauce thickens.',
      'Add beef and vegetables, simmer briefly. Serve with bagoong.',
    ],
  },
  {
    id: 'fil-sisig',
    name: 'Pork Sisig',
    imageUrl: PLACEHOLDER,
    category: 'Pork',
    area: 'Filipino',
    ingredients: ['pork belly', 'onion', 'garlic', 'chili pepper', 'soy sauce', 'calamansi', 'mayonnaise', 'egg', 'black pepper'],
    measurements: ['500 g', '1 pc', '4 cloves', '3 pcs', '3 tbsp', '4 pcs', '2 tbsp', '1 pc', '1 tsp'],
    steps: [
      'Boil pork belly until tender, then grill and chop finely.',
      'Sauté garlic, onion, and chili. Add the chopped pork.',
      'Season with soy sauce, calamansi juice, and pepper.',
      'Serve on a sizzling plate topped with mayo and a raw egg.',
    ],
  },
  {
    id: 'fil-lechon-kawali',
    name: 'Lechon Kawali',
    imageUrl: PLACEHOLDER,
    category: 'Pork',
    area: 'Filipino',
    ingredients: ['pork belly', 'salt', 'black pepper', 'bay leaf', 'garlic', 'vegetable oil', 'water'],
    measurements: ['1 kg', '2 tbsp', '1 tsp', '3 pcs', '6 cloves', '4 cups', '6 cups'],
    steps: [
      'Boil pork belly with salt, pepper, bay leaf, and garlic for 45 minutes.',
      'Drain and air-dry the pork completely.',
      'Deep-fry in hot oil until the skin is golden and crackling.',
      'Chop and serve with lechon sauce or spiced vinegar.',
    ],
  },
  {
    id: 'fil-crispy-pata',
    name: 'Crispy Pata',
    imageUrl: PLACEHOLDER,
    category: 'Pork',
    area: 'Filipino',
    ingredients: ['pork', 'salt', 'black pepper', 'bay leaf', 'garlic', 'soy sauce', 'vegetable oil', 'water'],
    measurements: ['1 pc (pata)', '2 tbsp', '1 tsp', '3 pcs', '6 cloves', '2 tbsp', '6 cups', '8 cups'],
    steps: [
      'Simmer pork leg with aromatics until tender, about 90 minutes.',
      'Air-dry the leg thoroughly.',
      'Deep-fry until the skin blisters and crisps.',
      'Serve with soy-vinegar dipping sauce.',
    ],
  },
  {
    id: 'fil-bicol-express',
    name: 'Bicol Express',
    imageUrl: PLACEHOLDER,
    category: 'Pork',
    area: 'Filipino',
    ingredients: ['pork belly', 'coconut milk', 'bagoong', 'chili pepper', 'garlic', 'onion', 'ginger'],
    measurements: ['500 g', '2 cups', '2 tbsp', '6 pcs', '4 cloves', '1 pc', '1 inch'],
    steps: [
      'Sauté garlic, onion, and ginger.',
      'Add pork and cook until lightly browned.',
      'Pour in coconut milk and bagoong, simmer for 20 minutes.',
      'Stir in chilies and reduce until the sauce is thick.',
    ],
  },
  {
    id: 'fil-kaldereta',
    name: 'Beef Kaldereta',
    imageUrl: PLACEHOLDER,
    category: 'Beef',
    area: 'Filipino',
    ingredients: ['beef', 'tomato sauce', 'liver spread', 'potato', 'carrot', 'bell pepper', 'green peas', 'garlic', 'onion', 'bay leaf', 'soy sauce', 'water'],
    measurements: ['1 kg', '1 cup', '1/2 cup', '2 pcs', '2 pcs', '1 pc', '1/2 cup', '4 cloves', '1 pc', '2 pcs', '2 tbsp', '4 cups'],
    steps: [
      'Brown beef cubes, then set aside.',
      'Sauté garlic and onion, return beef with soy sauce, tomato sauce, and water.',
      'Simmer until beef is tender, about 90 minutes.',
      'Add potatoes, carrots, liver spread, bell pepper, and peas. Cook until vegetables are done.',
    ],
  },
  {
    id: 'fil-menudo',
    name: 'Pork Menudo',
    imageUrl: PLACEHOLDER,
    category: 'Pork',
    area: 'Filipino',
    ingredients: ['pork', 'tomato sauce', 'potato', 'carrot', 'bell pepper', 'raisins', 'hotdog', 'garlic', 'onion', 'soy sauce', 'water'],
    measurements: ['500 g', '1 cup', '2 pcs', '1 pc', '1 pc', '1/4 cup', '4 pcs', '4 cloves', '1 pc', '2 tbsp', '2 cups'],
    steps: [
      'Sauté garlic and onion, add pork and brown.',
      'Stir in soy sauce, tomato sauce, and water. Simmer 30 minutes.',
      'Add potatoes, carrots, hotdogs, and raisins.',
      'Finish with bell pepper and cook until tender.',
    ],
  },
  {
    id: 'fil-afritada',
    name: 'Chicken Afritada',
    imageUrl: PLACEHOLDER,
    category: 'Chicken',
    area: 'Filipino',
    ingredients: ['chicken', 'tomato sauce', 'potato', 'carrot', 'bell pepper', 'garlic', 'onion', 'fish sauce', 'bay leaf', 'water'],
    measurements: ['1 kg', '1 cup', '2 pcs', '1 pc', '1 pc', '4 cloves', '1 pc', '2 tbsp', '2 pcs', '2 cups'],
    steps: [
      'Sauté garlic and onion, add chicken until lightly browned.',
      'Season with fish sauce, add tomato sauce, bay leaf, and water.',
      'Simmer for 25 minutes.',
      'Add potatoes, carrots, and bell pepper. Cook until vegetables are tender.',
    ],
  },
  {
    id: 'fil-bulalo',
    name: 'Bulalo',
    imageUrl: PLACEHOLDER,
    category: 'Beef',
    area: 'Filipino',
    ingredients: ['beef shank', 'onion', 'black pepper', 'cabbage', 'corn', 'potato', 'scallions', 'fish sauce', 'water'],
    measurements: ['1 kg', '1 pc', '1 tsp', '1/4 head', '2 pcs', '2 pcs', '2 stalks', '2 tbsp', '10 cups'],
    steps: [
      'Simmer beef shank with onion and pepper for 2 to 3 hours until tender.',
      'Add corn and potatoes, cook until soft.',
      'Finish with cabbage and scallions.',
      'Season with fish sauce and serve the broth hot.',
    ],
  },
  {
    id: 'fil-nilagang-baka',
    name: 'Nilagang Baka',
    imageUrl: PLACEHOLDER,
    category: 'Beef',
    area: 'Filipino',
    ingredients: ['beef', 'onion', 'potato', 'cabbage', 'sitaw', 'black pepper', 'fish sauce', 'water'],
    measurements: ['1 kg', '1 pc', '2 pcs', '1/4 head', '8 pcs', '1 tsp', '2 tbsp', '8 cups'],
    steps: [
      'Boil beef with onion and pepper until tender.',
      'Add potatoes and cook until soft.',
      'Drop in sitaw and cabbage near the end.',
      'Season with fish sauce and serve.',
    ],
  },
  {
    id: 'fil-pancit-canton',
    name: 'Pancit Canton',
    imageUrl: PLACEHOLDER,
    category: 'Noodles',
    area: 'Filipino',
    ingredients: ['canton', 'chicken', 'shrimp', 'cabbage', 'carrot', 'garlic', 'onion', 'soy sauce', 'oyster sauce', 'chicken stock'],
    measurements: ['500 g', '200 g', '200 g', '1/4 head', '1 pc', '4 cloves', '1 pc', '3 tbsp', '2 tbsp', '3 cups'],
    steps: [
      'Sauté garlic and onion, add chicken and shrimp.',
      'Pour in stock, soy sauce, and oyster sauce.',
      'Add vegetables and simmer briefly.',
      'Toss in canton noodles and cook until the sauce is absorbed.',
    ],
  },
  {
    id: 'fil-pancit-bihon',
    name: 'Pancit Bihon',
    imageUrl: PLACEHOLDER,
    category: 'Noodles',
    area: 'Filipino',
    ingredients: ['bihon', 'chicken', 'cabbage', 'carrot', 'garlic', 'onion', 'soy sauce', 'chicken stock', 'calamansi'],
    measurements: ['400 g', '200 g', '1/4 head', '1 pc', '4 cloves', '1 pc', '3 tbsp', '3 cups', '4 pcs'],
    steps: [
      'Soak bihon in water until pliable.',
      'Sauté garlic and onion, add chicken.',
      'Pour in stock and soy sauce, add vegetables.',
      'Add bihon and toss until cooked. Serve with calamansi.',
    ],
  },
  {
    id: 'fil-lumpiang-shanghai',
    name: 'Lumpiang Shanghai',
    imageUrl: PLACEHOLDER,
    category: 'Pork',
    area: 'Filipino',
    ingredients: ['ground pork', 'carrot', 'onion', 'garlic', 'egg', 'soy sauce', 'black pepper', 'lumpia wrapper', 'vegetable oil'],
    measurements: ['500 g', '1 pc', '1 pc', '4 cloves', '1 pc', '2 tbsp', '1 tsp', '1 pack', '3 cups'],
    steps: [
      'Mix pork with grated carrot, onion, garlic, egg, soy sauce, and pepper.',
      'Spoon filling onto wrappers and roll tightly.',
      'Deep-fry until golden brown.',
      'Drain and serve with sweet chili or banana ketchup.',
    ],
  },
  {
    id: 'fil-tortang-talong',
    name: 'Tortang Talong',
    imageUrl: PLACEHOLDER,
    category: 'Vegetarian',
    area: 'Filipino',
    ingredients: ['eggplant', 'egg', 'salt', 'black pepper', 'vegetable oil'],
    measurements: ['3 pcs', '3 pcs', '1/2 tsp', '1/4 tsp', '3 tbsp'],
    steps: [
      'Grill eggplants until the skin chars. Peel while keeping the stem.',
      'Flatten the eggplant and dip into beaten seasoned egg.',
      'Pan-fry until the egg sets on both sides.',
      'Serve with banana ketchup or a side of rice.',
    ],
  },
  {
    id: 'fil-ginisang-munggo',
    name: 'Ginisang Munggo',
    imageUrl: PLACEHOLDER,
    category: 'Soup',
    area: 'Filipino',
    ingredients: ['pork', 'garlic', 'onion', 'tomato', 'malunggay', 'fish sauce', 'water'],
    measurements: ['200 g', '4 cloves', '1 pc', '2 pcs', '1 bunch', '2 tbsp', '6 cups'],
    steps: [
      'Boil mung beans until soft.',
      'Sauté garlic, onion, tomato, and pork.',
      'Add cooked mung beans and simmer.',
      'Season with fish sauce and finish with malunggay.',
    ],
  },
  {
    id: 'fil-ginataang-gulay',
    name: 'Ginataang Gulay',
    imageUrl: PLACEHOLDER,
    category: 'Vegetarian',
    area: 'Filipino',
    ingredients: ['coconut milk', 'kalabasa', 'sitaw', 'shrimp', 'garlic', 'onion', 'ginger', 'bagoong'],
    measurements: ['2 cups', '400 g', '200 g', '150 g', '4 cloves', '1 pc', '1 inch', '2 tbsp'],
    steps: [
      'Sauté garlic, onion, and ginger.',
      'Add shrimp and bagoong, cook briefly.',
      'Pour coconut milk and add kalabasa; simmer until tender.',
      'Add sitaw and cook a few minutes more.',
    ],
  },
  {
    id: 'fil-filipino-spaghetti',
    name: 'Filipino-Style Spaghetti',
    imageUrl: PLACEHOLDER,
    category: 'Pasta',
    area: 'Filipino',
    ingredients: ['spaghetti', 'ground beef', 'hotdog', 'banana ketchup', 'tomato sauce', 'garlic', 'onion', 'brown sugar', 'cheese'],
    measurements: ['500 g', '300 g', '4 pcs', '1 cup', '1 cup', '4 cloves', '1 pc', '2 tbsp', '1/2 cup'],
    steps: [
      'Sauté garlic and onion, add ground beef until browned.',
      'Stir in banana ketchup, tomato sauce, and brown sugar.',
      'Add sliced hotdogs and simmer for 15 minutes.',
      'Toss with cooked spaghetti and top with grated cheese.',
    ],
  },
  {
    id: 'fil-arroz-caldo',
    name: 'Arroz Caldo',
    imageUrl: PLACEHOLDER,
    category: 'Rice',
    area: 'Filipino',
    ingredients: ['rice', 'chicken', 'ginger', 'garlic', 'onion', 'fish sauce', 'scallions', 'egg', 'calamansi', 'chicken stock'],
    measurements: ['1 cup', '500 g', '2 inches', '6 cloves', '1 pc', '2 tbsp', '2 stalks', '2 pcs', '4 pcs', '8 cups'],
    steps: [
      'Sauté ginger, garlic, and onion. Add chicken and fish sauce.',
      'Stir in rice, then pour in stock.',
      'Simmer until rice becomes porridge-like.',
      'Top with scallions, toasted garlic, boiled egg, and calamansi.',
    ],
  },
  {
    id: 'fil-tapsilog',
    name: 'Tapsilog',
    imageUrl: PLACEHOLDER,
    category: 'Beef',
    area: 'Filipino',
    ingredients: ['beef', 'soy sauce', 'calamansi', 'garlic', 'brown sugar', 'black pepper', 'rice', 'egg', 'vegetable oil'],
    measurements: ['500 g', '1/4 cup', '4 pcs', '6 cloves', '2 tbsp', '1 tsp', '3 cups', '3 pcs', '3 tbsp'],
    steps: [
      'Marinate thinly-sliced beef in soy sauce, calamansi, garlic, sugar, and pepper for at least an hour.',
      'Pan-fry the tapa until caramelized.',
      'Fry eggs sunny-side up and prepare garlic rice.',
      'Plate tapa, sinangag, and itlog together.',
    ],
  },
  {
    id: 'fil-longsilog',
    name: 'Longsilog',
    imageUrl: PLACEHOLDER,
    category: 'Pork',
    area: 'Filipino',
    ingredients: ['longganisa', 'rice', 'egg', 'garlic', 'vegetable oil', 'vinegar'],
    measurements: ['6 pcs', '3 cups', '3 pcs', '6 cloves', '3 tbsp', 'for dipping'],
    steps: [
      'Simmer longganisa in a bit of water until the water evaporates, then let it brown in its own oil.',
      'Make garlic fried rice with leftover rice and minced garlic.',
      'Fry eggs to preference.',
      'Serve with spiced vinegar on the side.',
    ],
  },
  {
    id: 'fil-inihaw-na-liempo',
    name: 'Inihaw na Liempo',
    imageUrl: PLACEHOLDER,
    category: 'Pork',
    area: 'Filipino',
    ingredients: ['pork belly', 'soy sauce', 'calamansi', 'banana ketchup', 'brown sugar', 'garlic', 'black pepper'],
    measurements: ['1 kg', '1/2 cup', '6 pcs', '1/4 cup', '2 tbsp', '6 cloves', '1 tsp'],
    steps: [
      'Marinate pork belly slices overnight.',
      'Grill over medium coals, basting with marinade.',
      'Cook until edges are charred and meat is cooked through.',
      'Rest briefly and serve with a soy-calamansi dip.',
    ],
  },
]
